# Example configuration

work-dir = "/home/shaun/devel/mpowered/lodjur/mpowered-services"

[redis]
host = "localhost"
port = 6379
database = 1

[git]
command = "git"
cache = "gitcache"
workdir = "workdirs"
debug = true

[nix-build]
command = "nix-build"
debug = true
