resolver: lts-12.6
packages:
- .

extra-deps:
  - Spock-0.13.0.0
  - Spock-core-0.13.0.0
  - Spock-lucid-0.4.0.1
  - reroute-0.5.0.0
  - git: https://github.com/freizl/hoauth2
    commit: d58808ff71c2ff15581115faabbf12d1a8ef679e
  - uri-bytestring-aeson-0.1.0.6

nix:
  shell-file: shell.nix
