resolver: lts-13.17
packages:
- .
- location: github
  extra-dep: true
- location:
    git: https://github.com/agrafix/Spock.git
    commit: 1ba2ac810321eacdf11fc99eed1c0a83e14e79d0
  extra-dep: true
  subdirs:
  - Spock
  - Spock-core
- location:
    git: https://github.com/bflyblue/servant-event-stream.git
    commit: 8bb90f1969d6fff3fb2e76d04ff86848ab0b5706
  extra-dep: true

extra-deps:
- Spock-lucid-0.4.0.1
- beam-migrate-0.4.0.1
- beam-postgres-0.4.0.0
- jwt-0.9.0
- primitive-extras-0.7.1
- reroute-0.5.0.0
- servant-github-webhook-0.4.1.0
- servant-pipes-0.15
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.2
